package com.example.androidadvancedday12.model

object UserList {
    val userList = listOf(
        User(1, "Dat", "Male", "Android"),
        User(2, "An", "Male", "Kotlin"),
        User(3, "Binh", "Male", "Java"),
        User(4, "Thanh", "Female", "PHP"),
        User(5, "Diem", "Female", ".NET"),
        User(6, "Lan", "Female", "React"),
        User(7, "Ha", "Female", "IOS"),
        User(8, "Tuan", "Male", "React"),
        User(9, "Bien", "Female", "PHP"),
        User(10, "Quy", "Male", "PHP"),
        User(11, "Tin", "Male", "Kotlin"),
        User(12, "Van", "Male", "NET"),
        User(13, "Phuong", "Female", "Java"),
        User(14, "Tuyet", "Female", "PHP"),
        User(15, "Nam", "Male", "React"),
        User(16, "Thao", "Female", "Java"),
        User(17, "Tho", "Female", "Kotlin"),
        User(18, "Vinh", "Male", "PHP"),
        User(19, "Phuc", "Female", "React"),
        User(20, "Dat", "Male", "Java"),
        User(21, "Huyen", "Female", "Kotlin"),
        User(22, "Hoang", "Female", "PHP"),
        User(23, "Thuy", "Female", "NET"),
        User(24, "Hue", "Male", "React"),
        User(25, "Vy", "Male", "PHP"),
        User(26, "Trang", "Female", "Java"),
        User(27, "Nhi", "Female", "Kotlin"),
        User(28, "Thanh", "Female", "NET"),
        User(29, "The", "Male", "Java"),
        User(30, "Dat", "Male", "React"),
        User(31, "Thong", "Male", "Java"),
        User(32, "Duc", "Female", "React"),
        User(33, "Vu", "Female", "PHP"),
        User(34, "Mo", "Male", "NET"),
        User(35, "Dang", "Male", "Kotlin"),
        User(36, "Hong", "Female", "NET"),
        User(37, "Ny", "Female", "Java"),
        User(38, "Mai", "Male", "Kotlin"),
        User(39, "Tuong", "Male", "React"),
        User(40, "Hoang", "Female", "PHP"),

    )
}